version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: always
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=inventory_management
      - DB_USERNAME=root
      - DB_PASSWORD=Saloni@123
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Saloni@123
      MYSQL_DATABASE: inventory_management
      MYSQL_USER: root
      MYSQL_PASSWORD: Saloni@123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
